### ISSUE TITLE
Changes to the CALL_ACTOR precompile

### ISSUE THREAD

**Issue by Stebalien** [Zondax/filecoin-solidity-api#52]
The CALL_ACTOR precompile now:

1. Must be called with DELEGATECALL (because it sends on behalf of the contract).
2. Takes an explicit `value` as the second parameter (after the method number).
3. Takes "send flags" as the third parameter (after the value). Currently, the only supported flag is 0x1 (read-only, i.e., staticcall).

All together:

1. method number (32 bytes)
2. value (32 bytes)
3. flags (32 bytes, only 0x0 and 0x1 are valid values where 0x1 means "static call").
4. codec (32 bytes)
5. address length (32 bytes)
6. params length (32 bytes)
7. params (arbitrary bytes)
8. address (arbitrary bytes)

(also note https://github.com/filecoin-project/ref-fvm/issues/1232, we messed up the ordering)
(we'd also appreciate feedback on how to make this precompile more usable)

:link: [zboto Link](https://app.clickup.com/t/396u03h)

**Comment by emmanuelm41** [comment]
@Stebalien is this change already on wallaby? where can we keep track of the upcoming updates and when they are happening. I guess we will need to update our integration test module with this update, and then update the code to do the call as you indicate here. @rllola will review it too.

**Comment by Stebalien** [comment]
We just released last night. I'll make sure to let you know about future issues that affect the precompiles.

**Comment by emmanuelm41** [comment]
@Stebalien It is on wallaby right now? I am not sure about it. Sorry for asking again!

**Comment by Stebalien** [comment]
It _should_ be.

**Comment by emmanuelm41** [comment]
Lola is currently working on it, so I assigned it to her.
