### ISSUE TITLE
Integration test for Multisig actor

### ISSUE THREAD

**Issue by ainhoa-a** [Zondax/filecoin-solidity-api#67]
:link: [zboto Link](https://app.clickup.com/t/39qt9j6)

**Comment by emmanuelm41** [comment]
We need to create a multisig actor, as it is not a singleton on the system. It works as Miner actor works. We should create a multisig actor first in order to be able to test its methods.

**Comment by emmanuelm41** [comment]
Multisig actor is not a singleton, so this issue is not necessary anymore. #76 creates a multisig actor and make use of it.
